# -*- coding: utf-8 -*-
"""grade_analyzer.py.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pqcFNNo6P19mNckXJQ69Vzp0sgprp_YB
"""

def process_scores(students):
    """Calculates the average score for each student."""
    averages = {}
    for name, scores in students.items():
        # Calculate average and round to 2 decimal places
        avg = round(sum(scores) / len(scores), 2)
        averages[name] = avg
    return averages

def classify_grades(averages):
    """Assigns letter grades based on internal thresholds."""
    # Local threshold variables
    threshold_a = 90
    threshold_b = 75
    threshold_c = 60

    classified = {}
    for name, avg in averages.items():
        if avg >= threshold_a:
            grade = 'A'
        elif avg >= threshold_b:
            grade = 'B'
        elif avg >= threshold_c:
            grade = 'C'
        else:
            grade = 'F'

        classified[name] = (avg, grade)
    return classified

def generate_report(classified, passing_avg=70):
    """Prints a formatted report and returns the number of passing students."""
    print("===== Student Grade Report =====")

    passed_count = 0
    total_students = len(classified)

    for name, (avg, grade) in classified.items():
        status = "PASS" if avg >= passing_avg else "FAIL"
        if status == "PASS":
            passed_count += 1

        # Format the output string for alignment
        print(f"{name:<10} | Avg: {avg:>6.2f} | Grade: {grade} | Status: {status}")

    print("=" * 32)
    print(f"Total Students : {total_students}")
    print(f"Passed         : {passed_count}")
    print(f"Failed         : {total_students - passed_count}")

    return passed_count

if __name__ == "__main__":
    # Sample data
    student_data = {
        "Alice": [85, 90, 82, 88],
        "Bob": [60, 65, 55, 70],
        "Clara": [95, 98, 92, 100],
        "Dave": [50, 45, 60, 52]
    }

    # Task 1: Process
    student_averages = process_scores(student_data)

    # Task 2: Classify
    graded_data = classify_grades(student_averages)

    # Task 3: Report
    total_passed = generate_report(graded_data, passing_avg=70)